language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"

script:
  - npm install
  - npm run lint
- name: Setup Node.js environment
  uses: actions/setup-node@v2.4.0
